server:
#  servlet:
  context-path: /joinmeds-service
  port: 8082
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://69.62.73.165:5432/join_meds
    username: yourusername
    password: 123ikm

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
file:
  upload-dir: uploads/photos
  resume-dir: uploads/resumes

smsbuddy:
  sendUrl: https://thesmsbuddy.com/api/v1/sms/send
  verifyUrl: https://thesmsbuddy.com/api/v1/otp/verify
  key: jKRvNILbt9W70LLJpE7hbS8Ifu5y3nto
  sender: JNMEDS
  type: 1
  templateId: "1707176562443508690"

otp:
    expiry:
      minutes: 5
